#!/usr/bin/env sh
set -eu

cd "$(dirname $0)"/..

server_port="${server_port:-8080}"

if [ $# -ne 2 ]; then
    1>&2 echo "missing required arguments"
    1>&2 echo "usage: $0 field value"
    1>&2 echo "example: $0 '\"indicators\", \"indicator\"' '\"85.93.20.243\"'"
    1>&2 echo "example: $0 '\"author_name\"' '\"bijay\"'"
    1>&2 echo "example: $0 '\"indicators\", \"id\"' '460576'"
    exit 1
fi
field="$1"
shift
value="$1"
shift

verbose="${verbose:-0}"
case "$verbose" in
    [1yY]*)
        verbose=1
        ;;
    *)
        verbose=0
        ;;
esac


# ex: {"field": ["indicators", "indicator"], "value": "85.93.20.243"}
json_payload="{\"field\": [$field], \"value\": $value}"
if [ "$verbose" -eq 1 ]; then
    echo "json: $json_payload"
fi

exec curl -v --json "$json_payload" "$@" "http://localhost:${server_port}/search"
